#define SIOCTL_TYPE 40000
#define IOCTL_FILTER_ENABLE CTL_CODE( SIOCTL_TYPE, 0x01, METHOD_NEITHER , FILE_ANY_ACCESS  )
#define IOCTL_FILTER_DISABLE CTL_CODE( SIOCTL_TYPE, 0x02, METHOD_NEITHER , FILE_ANY_ACCESS  )

